const GET_PRODUCTS = 'GET_PRODUCTS';
const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';
const ADD_TO_CART = 'ADD_TO_CART';
const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';

export {
  ADD_TO_CART,
  GET_PRODUCTS,
  GET_PRODUCTS_SUCCESS,
  GET_PRODUCTS_FAIL,
  REMOVE_CART_ITEM
};
